# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    default: 5000
    description: MLflow server port.
    type: int
  host:
    default: 0.0.0.0
    description: MLflow server host.
    type: string
