# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    default: 5000
    description: MLflow server port.
    type: int
  host:
    default: mlflow.server
    description: MLflow server host. Used by ingress.
    type: string
